# Generated by Django 4.1 on 2022-08-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('berat_max', models.PositiveIntegerField()),
                ('berat_min', models.PositiveIntegerField()),
            ],
        ),
    ]
